package ctrl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import main.Mapiranje;
import repo.UserRepository;

@Controller
@RequestMapping(path="/demo")
public class MainController {
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewPayment (@RequestParam long id
	, @RequestParam String tip,@RequestParam int broj,@RequestParam short security_code
	,@RequestParam String datum_isteka,@RequestParam String nosilac_karte
	,@RequestParam String korisnik_kartice_id,@RequestParam int stanje) {
// @ResponseBody means the returned String is the response, not a view name
// @RequestParam means it is a parameter from the GET or POST request

		Mapiranje n = new Mapiranje(id,tip,broj,security_code,datum_isteka,korisnik_kartice_id, nosilac_karte, stanje);
n.setId(id);
n.setTip(tip);
n.setBroj(broj);
n.setDatum_isteka(datum_isteka);
n.setNosilac_kartice(nosilac_karte);
n.setKorisnik_kartice_id(korisnik_kartice_id);
n.setSecurity_code(security_code);
userRepository.save(n);
return "Saved";
}

@GetMapping(path="/all")
public @ResponseBody Iterable<Mapiranje> getAllUsers() {
// This returns a JSON or XML with the users
return userRepository.findAll();
}
}
