#spring:
 # datasource:
  #  driverClassName: com.mysql.jdbc.Driver
   # url: jdbc:mysql://sql7.freemysqlhosting.net:3306/sql7291155
   # username: sql7291155
   # password: 1SKY8jmI7x
  #jpa:
   # hibernate.ddl-auto: update
    #generate-ddl: true
    #show-sql: true
spring:
  application:
    name: PAYMENTS
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payments?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 8083

